# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varapp', '0001_squashed_0003_auto_20160303_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantsdb',
            old_name='path',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='variantsdb',
            name='hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variantsdb',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
