# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varapp', '0002_auto_20160315_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantsdb',
            name='visible_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variantsdb',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='variantsdb',
            name='location',
            field=models.TextField(default='', null=True),
        ),
    ]
