# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varapp', '0004_auto_20160517_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantsdb',
            name='parent_db',
        ),
        migrations.AddField(
            model_name='variantsdb',
            name='parent_db_id',
            field=models.IntegerField(null=True),
        ),
    ]
