# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varapp', '0005_auto_20160523_1357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dbaccess',
            unique_together=set([('user', 'variants_db')]),
        ),
        migrations.AlterUniqueTogether(
            name='variantsdb',
            unique_together=set([('filename', 'hash')]),
        ),
    ]
