
GENOTYPE_ACTIVE = 'active'
GENOTYPE_DOMINANT = 'dominant'
GENOTYPE_RECESSIVE = 'recessive'
GENOTYPE_DENOVO = 'de_novo'
GENOTYPE_COMPOUND = 'compound_het'
GENOTYPE_XLINKED = 'x_linked'
GENOTYPE_FILTERS = [GENOTYPE_ACTIVE, GENOTYPE_DOMINANT, GENOTYPE_RECESSIVE,
                    GENOTYPE_DENOVO, GENOTYPE_COMPOUND, GENOTYPE_XLINKED]

GENOTYPE_BIT_NON_CARRIER=1
GENOTYPE_BIT_CARRIER_HET=2
GENOTYPE_BIT_CARRIER_HOM=4
GENOTYPE_BIT_CARRIER=2+4
GENOTYPE_BIT_NOT_CARRIER_HOM=1+2
GENOTYPE_BIT_ANY=1+2+4
GENOTYPE_BIT_UNKNOWN=64

